export type CurrencyMeta = {
  isoNumeric: string;
  name: string;
  symbol: string;
  flagIcon: string;
  popular: boolean;
  order: number | undefined;
};

export const currencyMeta: Record<string, CurrencyMeta>
  = {
    AED: {
      isoNumeric: "784",
      name: "United Arab Emirates Dirham",
      symbol: "د.إ",
      flagIcon: "circle-flags:ae",
      popular: false,
      order: 0,
    },
    AFN: {
      isoNumeric: "971",
      name: "Afghan Afghani",
      symbol: "؋",
      flagIcon: "circle-flags:af",
      popular: false,
      order: 0,
    },
    ALL: {
      isoNumeric: "008",
      name: "Albanian Lek",
      symbol: "L",
      flagIcon: "circle-flags:al",
      popular: false,
      order: 0,
    },
    AMD: {
      isoNumeric: "051",
      name: "Armenian Dram",
      symbol: "֏",
      flagIcon: "circle-flags:am",
      popular: false,
      order: 0,
    },
    ANG: {
      isoNumeric: "532",
      name: "Netherlands Antillean Gulden",
      symbol: "ƒ",
      flagIcon: "circle-flags:cw",
      popular: false,
      order: 0,
    },
    AOA: {
      isoNumeric: "973",
      name: "Angolan Kwanza",
      symbol: "Kz",
      flagIcon: "circle-flags:ao",
      popular: false,
      order: 0,
    },
    ARS: {
      isoNumeric: "032",
      name: "Argentine Peso",
      symbol: "$",
      flagIcon: "circle-flags:ar",
      popular: false,
      order: 0,
    },
    AUD: {
      isoNumeric: "036",
      name: "Australian Dollar",
      symbol: "$",
      flagIcon: "circle-flags:au",
      popular: false,
      order: 0,
    },
    AWG: {
      isoNumeric: "533",
      name: "Aruban Florin",
      symbol: "ƒ",
      flagIcon: "circle-flags:aw",
      popular: false,
      order: 0,
    },
    AZN: {
      isoNumeric: "944",
      name: "Azerbaijani Manat",
      symbol: "₼",
      flagIcon: "circle-flags:az",
      popular: false,
      order: 0,
    },
    BAM: {
      isoNumeric: "977",
      name: "Bosnia and Herzegovina Convertible Mark",
      symbol: "КМ",
      flagIcon: "circle-flags:ba",
      popular: false,
      order: 0,
    },
    BBD: {
      isoNumeric: "052",
      name: "Barbadian Dollar",
      symbol: "$",
      flagIcon: "circle-flags:bb",
      popular: false,
      order: 0,
    },
    BDT: {
      isoNumeric: "050",
      name: "Bangladeshi Taka",
      symbol: "৳",
      flagIcon: "circle-flags:bd",
      popular: false,
      order: 0,
    },
    BHD: {
      isoNumeric: "048",
      name: "Bahraini Dinar",
      symbol: "د.ب",
      flagIcon: "circle-flags:bh",
      popular: false,
      order: 0,
    },
    BIF: {
      isoNumeric: "108",
      name: "Burundian Franc",
      symbol: "Fr",
      flagIcon: "circle-flags:bi",
      popular: false,
      order: 0,
    },
    BMD: {
      isoNumeric: "060",
      name: "Bermudian Dollar",
      symbol: "$",
      flagIcon: "circle-flags:bm",
      popular: false,
      order: 0,
    },
    BND: {
      isoNumeric: "096",
      name: "Brunei Dollar",
      symbol: "$",
      flagIcon: "circle-flags:bn",
      popular: false,
      order: 0,
    },
    BOB: {
      isoNumeric: "068",
      name: "Bolivian Boliviano",
      symbol: "Bs.",
      flagIcon: "circle-flags:bo",
      popular: false,
      order: 0,
    },
    BRL: {
      isoNumeric: "986",
      name: "Brazilian Real",
      symbol: "R$",
      flagIcon: "circle-flags:br",
      popular: false,
      order: 0,
    },
    BSD: {
      isoNumeric: "044",
      name: "Bahamian Dollar",
      symbol: "$",
      flagIcon: "circle-flags:bs",
      popular: false,
      order: 0,
    },
    BTN: {
      isoNumeric: "064",
      name: "Bhutanese Ngultrum",
      symbol: "Nu.",
      flagIcon: "circle-flags:bt",
      popular: false,
      order: 0,
    },
    BWP: {
      isoNumeric: "072",
      name: "Botswana Pula",
      symbol: "P",
      flagIcon: "circle-flags:bw",
      popular: false,
      order: 0,
    },
    BYN: {
      isoNumeric: "933",
      name: "Belarusian Ruble",
      symbol: "Br",
      flagIcon: "circle-flags:by",
      popular: false,
      order: 0,
    },
    BZD: {
      isoNumeric: "084",
      name: "Belize Dollar",
      symbol: "$",
      flagIcon: "circle-flags:bz",
      popular: false,
      order: 0,
    },
    CAD: {
      isoNumeric: "124",
      name: "Canadian Dollar",
      symbol: "$",
      flagIcon: "circle-flags:ca",
      popular: false,
      order: 0,
    },
    CDF: {
      isoNumeric: "976",
      name: "Congolese Franc",
      symbol: "Fr",
      flagIcon: "circle-flags:cd",
      popular: false,
      order: 0,
    },
    CHF: {
      isoNumeric: "756",
      name: "Swiss Franc",
      symbol: "CHF",
      flagIcon: "circle-flags:ch",
      popular: false,
      order: 0,
    },
    CLP: {
      isoNumeric: "152",
      name: "Chilean Peso",
      symbol: "$",
      flagIcon: "circle-flags:cl",
      popular: false,
      order: 0,
    },
    CNH: {
      isoNumeric: "",
      name: "Chinese Renminbi Yuan Offshore",
      symbol: "¥",
      flagIcon: "ion:star",
      popular: false,
      order: 0,
    },
    CNY: {
      isoNumeric: "156",
      name: "Chinese Renminbi Yuan",
      symbol: "¥",
      flagIcon: "circle-flags:cn",
      popular: false,
      order: 0,
    },
    COP: {
      isoNumeric: "170",
      name: "Colombian Peso",
      symbol: "$",
      flagIcon: "circle-flags:co",
      popular: false,
      order: 0,
    },
    CRC: {
      isoNumeric: "188",
      name: "Costa Rican Colón",
      symbol: "₡",
      flagIcon: "circle-flags:cr",
      popular: false,
      order: 0,
    },
    CUP: {
      isoNumeric: "192",
      name: "Cuban Peso",
      symbol: "$",
      flagIcon: "circle-flags:cu",
      popular: false,
      order: 0,
    },
    CVE: {
      isoNumeric: "132",
      name: "Cape Verdean Escudo",
      symbol: "$",
      flagIcon: "circle-flags:cv",
      popular: false,
      order: 0,
    },
    CZK: {
      isoNumeric: "203",
      name: "Czech Koruna",
      symbol: "Kč",
      flagIcon: "circle-flags:cz",
      popular: false,
      order: 0,
    },
    DJF: {
      isoNumeric: "262",
      name: "Djiboutian Franc",
      symbol: "Fdj",
      flagIcon: "circle-flags:dj",
      popular: false,
      order: 0,
    },
    DKK: {
      isoNumeric: "208",
      name: "Danish Krone",
      symbol: "kr.",
      flagIcon: "circle-flags:dk",
      popular: false,
      order: 0,
    },
    DOP: {
      isoNumeric: "214",
      name: "Dominican Peso",
      symbol: "$",
      flagIcon: "circle-flags:do",
      popular: false,
      order: 0,
    },
    DZD: {
      isoNumeric: "012",
      name: "Algerian Dinar",
      symbol: "د.ج",
      flagIcon: "circle-flags:dz",
      popular: false,
      order: 0,
    },
    EGP: {
      isoNumeric: "818",
      name: "Egyptian Pound",
      symbol: "ج.م",
      flagIcon: "circle-flags:eg",
      popular: false,
      order: 0,
    },
    ERN: {
      isoNumeric: "232",
      name: "Eritrean Nakfa",
      symbol: "Nfk",
      flagIcon: "circle-flags:er",
      popular: false,
      order: 0,
    },
    ETB: {
      isoNumeric: "230",
      name: "Ethiopian Birr",
      symbol: "Br",
      flagIcon: "circle-flags:et",
      popular: false,
      order: 0,
    },
    EUR: {
      isoNumeric: "978",
      name: "Euro",
      symbol: "€",
      flagIcon: "circle-flags:eu",
      popular: true,
      order: 0,
    },
    FJD: {
      isoNumeric: "242",
      name: "Fijian Dollar",
      symbol: "$",
      flagIcon: "circle-flags:fj",
      popular: false,
      order: 0,
    },
    FKP: {
      isoNumeric: "238",
      name: "Falkland Pound",
      symbol: "£",
      flagIcon: "circle-flags:fk",
      popular: false,
      order: 0,
    },
    GBP: {
      isoNumeric: "826",
      name: "British Pound",
      symbol: "£",
      flagIcon: "circle-flags:gb",
      popular: true,
      order: 0,
    },
    GEL: {
      isoNumeric: "981",
      name: "Georgian Lari",
      symbol: "₾",
      flagIcon: "circle-flags:ge",
      popular: false,
      order: 0,
    },
    GGP: {
      isoNumeric: "",
      name: "Guernsey Pound",
      symbol: "£",
      flagIcon: "ion:star",
      popular: false,
      order: 0,
    },
    GHS: {
      isoNumeric: "936",
      name: "Ghanaian Cedi",
      symbol: "₵",
      flagIcon: "circle-flags:gh",
      popular: false,
      order: 0,
    },
    GIP: {
      isoNumeric: "292",
      name: "Gibraltar Pound",
      symbol: "£",
      flagIcon: "circle-flags:gi",
      popular: false,
      order: 0,
    },
    GMD: {
      isoNumeric: "270",
      name: "Gambian Dalasi",
      symbol: "D",
      flagIcon: "circle-flags:gm",
      popular: false,
      order: 0,
    },
    GNF: {
      isoNumeric: "324",
      name: "Guinean Franc",
      symbol: "Fr",
      flagIcon: "circle-flags:gn",
      popular: false,
      order: 0,
    },
    GTQ: {
      isoNumeric: "320",
      name: "Guatemalan Quetzal",
      symbol: "Q",
      flagIcon: "circle-flags:gt",
      popular: false,
      order: 0,
    },
    GYD: {
      isoNumeric: "328",
      name: "Guyanese Dollar",
      symbol: "$",
      flagIcon: "circle-flags:gy",
      popular: false,
      order: 0,
    },
    HKD: {
      isoNumeric: "344",
      name: "Hong Kong Dollar",
      symbol: "$",
      flagIcon: "circle-flags:hk",
      popular: false,
      order: 0,
    },
    HNL: {
      isoNumeric: "340",
      name: "Honduran Lempira",
      symbol: "L",
      flagIcon: "circle-flags:hn",
      popular: false,
      order: 0,
    },
    HTG: {
      isoNumeric: "332",
      name: "Haitian Gourde",
      symbol: "G",
      flagIcon: "circle-flags:ht",
      popular: false,
      order: 0,
    },
    HUF: {
      isoNumeric: "348",
      name: "Hungarian Forint",
      symbol: "Ft",
      flagIcon: "circle-flags:hu",
      popular: false,
      order: 0,
    },
    IDR: {
      isoNumeric: "360",
      name: "Indonesian Rupiah",
      symbol: "Rp",
      flagIcon: "circle-flags:id",
      popular: false,
      order: 0,
    },
    ILS: {
      isoNumeric: "376",
      name: "Israeli New Shekel",
      symbol: "₪",
      flagIcon: "circle-flags:il",
      popular: false,
      order: 0,
    },
    IMP: {
      isoNumeric: "",
      name: "Isle of Man Pound",
      symbol: "£",
      flagIcon: "ion:star",
      popular: false,
      order: 0,
    },
    INR: {
      isoNumeric: "356",
      name: "Indian Rupee",
      symbol: "₹",
      flagIcon: "circle-flags:in",
      popular: false,
      order: 0,
    },
    IQD: {
      isoNumeric: "368",
      name: "Iraqi Dinar",
      symbol: "ع.د",
      flagIcon: "circle-flags:iq",
      popular: false,
      order: 0,
    },
    IRR: {
      isoNumeric: "364",
      name: "Iranian Rial",
      symbol: "﷼",
      flagIcon: "circle-flags:ir",
      popular: false,
      order: 0,
    },
    ISK: {
      isoNumeric: "352",
      name: "Icelandic Króna",
      symbol: "kr.",
      flagIcon: "circle-flags:is",
      popular: false,
      order: 0,
    },
    JEP: {
      isoNumeric: "",
      name: "Jersey Pound",
      symbol: "£",
      flagIcon: "ion:star",
      popular: false,
      order: 0,
    },
    JMD: {
      isoNumeric: "388",
      name: "Jamaican Dollar",
      symbol: "$",
      flagIcon: "circle-flags:jm",
      popular: false,
      order: 0,
    },
    JOD: {
      isoNumeric: "400",
      name: "Jordanian Dinar",
      symbol: "د.ا",
      flagIcon: "circle-flags:jo",
      popular: false,
      order: 0,
    },
    JPY: {
      isoNumeric: "392",
      name: "Japanese Yen",
      symbol: "¥",
      flagIcon: "circle-flags:jp",
      popular: false,
      order: 0,
    },
    KES: {
      isoNumeric: "404",
      name: "Kenyan Shilling",
      symbol: "KSh",
      flagIcon: "circle-flags:ke",
      popular: false,
      order: 0,
    },
    KGS: {
      isoNumeric: "417",
      name: "Kyrgyzstani Som",
      symbol: "som",
      flagIcon: "circle-flags:kg",
      popular: false,
      order: 0,
    },
    KHR: {
      isoNumeric: "116",
      name: "Cambodian Riel",
      symbol: "៛",
      flagIcon: "circle-flags:kh",
      popular: false,
      order: 0,
    },
    KMF: {
      isoNumeric: "174",
      name: "Comorian Franc",
      symbol: "Fr",
      flagIcon: "circle-flags:km",
      popular: false,
      order: 0,
    },
    KPW: {
      isoNumeric: "408",
      name: "North Korean Won",
      symbol: "₩",
      flagIcon: "circle-flags:kp",
      popular: false,
      order: 0,
    },
    KRW: {
      isoNumeric: "410",
      name: "South Korean Won",
      symbol: "₩",
      flagIcon: "circle-flags:kr",
      popular: false,
      order: 0,
    },
    KWD: {
      isoNumeric: "414",
      name: "Kuwaiti Dinar",
      symbol: "د.ك",
      flagIcon: "circle-flags:kw",
      popular: false,
      order: 0,
    },
    KYD: {
      isoNumeric: "136",
      name: "Cayman Islands Dollar",
      symbol: "$",
      flagIcon: "circle-flags:ky",
      popular: false,
      order: 0,
    },
    KZT: {
      isoNumeric: "398",
      name: "Kazakhstani Tenge",
      symbol: "₸",
      flagIcon: "circle-flags:kz",
      popular: false,
      order: 0,
    },
    LAK: {
      isoNumeric: "418",
      name: "Lao Kip",
      symbol: "₭",
      flagIcon: "circle-flags:la",
      popular: false,
      order: 0,
    },
    LBP: {
      isoNumeric: "422",
      name: "Lebanese Pound",
      symbol: "ل.ل",
      flagIcon: "circle-flags:lb",
      popular: false,
      order: 0,
    },
    LKR: {
      isoNumeric: "144",
      name: "Sri Lankan Rupee",
      symbol: "₨",
      flagIcon: "circle-flags:lk",
      popular: false,
      order: 0,
    },
    LRD: {
      isoNumeric: "430",
      name: "Liberian Dollar",
      symbol: "$",
      flagIcon: "circle-flags:lr",
      popular: false,
      order: 0,
    },
    LSL: {
      isoNumeric: "426",
      name: "Lesotho Loti",
      symbol: "L",
      flagIcon: "circle-flags:ls",
      popular: false,
      order: 0,
    },
    LYD: {
      isoNumeric: "434",
      name: "Libyan Dinar",
      symbol: "ل.د",
      flagIcon: "circle-flags:ly",
      popular: false,
      order: 0,
    },
    MAD: {
      isoNumeric: "504",
      name: "Moroccan Dirham",
      symbol: "د.م.",
      flagIcon: "circle-flags:ma",
      popular: false,
      order: 0,
    },
    MDL: {
      isoNumeric: "498",
      name: "Moldovan Leu",
      symbol: "L",
      flagIcon: "circle-flags:md",
      popular: false,
      order: 0,
    },
    MGA: {
      isoNumeric: "969",
      name: "Malagasy Ariary",
      symbol: "Ar",
      flagIcon: "circle-flags:mg",
      popular: false,
      order: 0,
    },
    MKD: {
      isoNumeric: "807",
      name: "Macedonian Denar",
      symbol: "ден",
      flagIcon: "circle-flags:mk",
      popular: false,
      order: 0,
    },
    MMK: {
      isoNumeric: "104",
      name: "Myanmar Kyat",
      symbol: "K",
      flagIcon: "circle-flags:mm",
      popular: false,
      order: 0,
    },
    MNT: {
      isoNumeric: "496",
      name: "Mongolian Tögrög",
      symbol: "₮",
      flagIcon: "circle-flags:mn",
      popular: false,
      order: 0,
    },
    MOP: {
      isoNumeric: "446",
      name: "Macanese Pataca",
      symbol: "P",
      flagIcon: "circle-flags:mo",
      popular: false,
      order: 0,
    },
    MRO: {
      isoNumeric: "478",
      name: "Mauritanian Ouguiya",
      symbol: "UM",
      flagIcon: "ion:star",
      popular: false,
      order: 0,
    },
    MRU: {
      isoNumeric: "929",
      name: "Mauritanian Ouguiya",
      symbol: "UM",
      flagIcon: "circle-flags:mr",
      popular: false,
      order: 0,
    },
    MUR: {
      isoNumeric: "480",
      name: "Mauritian Rupee",
      symbol: "₨",
      flagIcon: "circle-flags:mu",
      popular: false,
      order: 0,
    },
    MVR: {
      isoNumeric: "462",
      name: "Maldivian Rufiyaa",
      symbol: "MVR",
      flagIcon: "circle-flags:mv",
      popular: false,
      order: 0,
    },
    MWK: {
      isoNumeric: "454",
      name: "Malawian Kwacha",
      symbol: "MK",
      flagIcon: "circle-flags:mw",
      popular: false,
      order: 0,
    },
    MXN: {
      isoNumeric: "484",
      name: "Mexican Peso",
      symbol: "$",
      flagIcon: "circle-flags:mx",
      popular: false,
      order: 0,
    },
    MYR: {
      isoNumeric: "458",
      name: "Malaysian Ringgit",
      symbol: "RM",
      flagIcon: "circle-flags:my",
      popular: false,
      order: 0,
    },
    MZN: {
      isoNumeric: "943",
      name: "Mozambican Metical",
      symbol: "MTn",
      flagIcon: "circle-flags:mz",
      popular: false,
      order: 0,
    },
    NAD: {
      isoNumeric: "516",
      name: "Namibian Dollar",
      symbol: "$",
      flagIcon: "circle-flags:na",
      popular: false,
      order: 0,
    },
    NGN: {
      isoNumeric: "566",
      name: "Nigerian Naira",
      symbol: "₦",
      flagIcon: "circle-flags:ng",
      popular: false,
      order: 0,
    },
    NIO: {
      isoNumeric: "558",
      name: "Nicaraguan Córdoba",
      symbol: "C$",
      flagIcon: "circle-flags:ni",
      popular: false,
      order: 0,
    },
    NOK: {
      isoNumeric: "578",
      name: "Norwegian Krone",
      symbol: "kr",
      flagIcon: "circle-flags:no",
      popular: false,
      order: 0,
    },
    NPR: {
      isoNumeric: "524",
      name: "Nepalese Rupee",
      symbol: "Rs.",
      flagIcon: "circle-flags:np",
      popular: false,
      order: 0,
    },
    NZD: {
      isoNumeric: "554",
      name: "New Zealand Dollar",
      symbol: "$",
      flagIcon: "circle-flags:nz",
      popular: false,
      order: 0,
    },
    OMR: {
      isoNumeric: "512",
      name: "Omani Rial",
      symbol: "ر.ع.",
      flagIcon: "circle-flags:om",
      popular: false,
      order: 0,
    },
    PAB: {
      isoNumeric: "590",
      name: "Panamanian Balboa",
      symbol: "B/.",
      flagIcon: "circle-flags:pa",
      popular: false,
      order: 0,
    },
    PEN: {
      isoNumeric: "604",
      name: "Peruvian Sol",
      symbol: "S/",
      flagIcon: "circle-flags:pe",
      popular: false,
      order: 0,
    },
    PGK: {
      isoNumeric: "598",
      name: "Papua New Guinean Kina",
      symbol: "K",
      flagIcon: "circle-flags:pg",
      popular: false,
      order: 0,
    },
    PHP: {
      isoNumeric: "608",
      name: "Philippine Peso",
      symbol: "₱",
      flagIcon: "circle-flags:ph",
      popular: false,
      order: 0,
    },
    PKR: {
      isoNumeric: "586",
      name: "Pakistani Rupee",
      symbol: "₨",
      flagIcon: "circle-flags:pk",
      popular: false,
      order: 0,
    },
    PLN: {
      isoNumeric: "985",
      name: "Polish Złoty",
      symbol: "zł",
      flagIcon: "circle-flags:pl",
      popular: false,
      order: 0,
    },
    PYG: {
      isoNumeric: "600",
      name: "Paraguayan Guaraní",
      symbol: "₲",
      flagIcon: "circle-flags:py",
      popular: false,
      order: 0,
    },
    QAR: {
      isoNumeric: "634",
      name: "Qatari Riyal",
      symbol: "ر.ق",
      flagIcon: "circle-flags:qa",
      popular: false,
      order: 0,
    },
    RON: {
      isoNumeric: "946",
      name: "Romanian Leu",
      symbol: "Lei",
      flagIcon: "circle-flags:ro",
      popular: false,
      order: 0,
    },
    RSD: {
      isoNumeric: "941",
      name: "Serbian Dinar",
      symbol: "RSD",
      flagIcon: "circle-flags:rs",
      popular: false,
      order: 0,
    },
    RUB: {
      isoNumeric: "643",
      name: "Russian Ruble",
      symbol: "₽",
      flagIcon: "circle-flags:ru",
      popular: false,
      order: 0,
    },
    RWF: {
      isoNumeric: "646",
      name: "Rwandan Franc",
      symbol: "FRw",
      flagIcon: "circle-flags:rw",
      popular: false,
      order: 0,
    },
    SAR: {
      isoNumeric: "682",
      name: "Saudi Riyal",
      symbol: "ر.س",
      flagIcon: "circle-flags:sa",
      popular: false,
      order: 0,
    },
    SBD: {
      isoNumeric: "090",
      name: "Solomon Islands Dollar",
      symbol: "$",
      flagIcon: "circle-flags:sb",
      popular: false,
      order: 0,
    },
    SCR: {
      isoNumeric: "690",
      name: "Seychellois Rupee",
      symbol: "₨",
      flagIcon: "circle-flags:sc",
      popular: false,
      order: 0,
    },
    SDG: {
      isoNumeric: "938",
      name: "Sudanese Pound",
      symbol: "£",
      flagIcon: "circle-flags:sd",
      popular: false,
      order: 0,
    },
    SEK: {
      isoNumeric: "752",
      name: "Swedish Krona",
      symbol: "kr",
      flagIcon: "circle-flags:se",
      popular: false,
      order: 0,
    },
    SGD: {
      isoNumeric: "702",
      name: "Singapore Dollar",
      symbol: "$",
      flagIcon: "circle-flags:sg",
      popular: false,
      order: 0,
    },
    SHP: {
      isoNumeric: "654",
      name: "Saint Helenian Pound",
      symbol: "£",
      flagIcon: "circle-flags:sh",
      popular: false,
      order: 0,
    },
    SLE: {
      isoNumeric: "925",
      name: "New Leone",
      symbol: "Le",
      flagIcon: "circle-flags:sl",
      popular: false,
      order: 0,
    },
    SOS: {
      isoNumeric: "706",
      name: "Somali Shilling",
      symbol: "Sh",
      flagIcon: "circle-flags:so",
      popular: false,
      order: 0,
    },
    SRD: {
      isoNumeric: "968",
      name: "Surinamese Dollar",
      symbol: "$",
      flagIcon: "circle-flags:sr",
      popular: false,
      order: 0,
    },
    SSP: {
      isoNumeric: "728",
      name: "South Sudanese Pound",
      symbol: "£",
      flagIcon: "circle-flags:ss",
      popular: false,
      order: 0,
    },
    STN: {
      isoNumeric: "930",
      name: "São Tomé and Príncipe Second Dobra",
      symbol: "Db",
      flagIcon: "circle-flags:st",
      popular: false,
      order: 0,
    },
    SVC: {
      isoNumeric: "222",
      name: "Salvadoran Colón",
      symbol: "₡",
      flagIcon: "circle-flags:sv",
      popular: false,
      order: 0,
    },
    SYP: {
      isoNumeric: "760",
      name: "Syrian Pound",
      symbol: "£S",
      flagIcon: "circle-flags:sy",
      popular: false,
      order: 0,
    },
    SZL: {
      isoNumeric: "748",
      name: "Swazi Lilangeni",
      symbol: "E",
      flagIcon: "circle-flags:sz",
      popular: false,
      order: 0,
    },
    THB: {
      isoNumeric: "764",
      name: "Thai Baht",
      symbol: "฿",
      flagIcon: "circle-flags:th",
      popular: false,
      order: 0,
    },
    TJS: {
      isoNumeric: "972",
      name: "Tajikistani Somoni",
      symbol: "ЅМ",
      flagIcon: "circle-flags:tj",
      popular: false,
      order: 0,
    },
    TMT: {
      isoNumeric: "934",
      name: "Turkmenistani Manat",
      symbol: "m",
      flagIcon: "circle-flags:tm",
      popular: false,
      order: 0,
    },
    TND: {
      isoNumeric: "788",
      name: "Tunisian Dinar",
      symbol: "د.ت",
      flagIcon: "circle-flags:tn",
      popular: false,
      order: 0,
    },
    TOP: {
      isoNumeric: "776",
      name: "Tongan Paʻanga",
      symbol: "T$",
      flagIcon: "circle-flags:to",
      popular: false,
      order: 0,
    },
    TRY: {
      isoNumeric: "949",
      name: "Turkish Lira",
      symbol: "₺",
      flagIcon: "circle-flags:tr",
      popular: false,
      order: 0,
    },
    TTD: {
      isoNumeric: "780",
      name: "Trinidad and Tobago Dollar",
      symbol: "$",
      flagIcon: "circle-flags:tt",
      popular: false,
      order: 0,
    },
    TWD: {
      isoNumeric: "901",
      name: "New Taiwan Dollar",
      symbol: "$",
      flagIcon: "circle-flags:tw",
      popular: false,
      order: 0,
    },
    TZS: {
      isoNumeric: "834",
      name: "Tanzanian Shilling",
      symbol: "Sh",
      flagIcon: "circle-flags:tz",
      popular: false,
      order: 0,
    },
    UAH: {
      isoNumeric: "980",
      name: "Ukrainian Hryvnia",
      symbol: "₴",
      flagIcon: "circle-flags:ua",
      popular: false,
      order: 0,
    },
    UGX: {
      isoNumeric: "800",
      name: "Ugandan Shilling",
      symbol: "USh",
      flagIcon: "circle-flags:ug",
      popular: false,
      order: 0,
    },
    USD: {
      isoNumeric: "840",
      name: "United States Dollar",
      symbol: "$",
      flagIcon: "circle-flags:us",
      popular: true,
      order: 0,
    },
    UYU: {
      isoNumeric: "858",
      name: "Uruguayan Peso",
      symbol: "$U",
      flagIcon: "circle-flags:uy",
      popular: false,
      order: 0,
    },
    UZS: {
      isoNumeric: "860",
      name: "Uzbekistan Som",
      symbol: "so'm",
      flagIcon: "circle-flags:uz",
      popular: false,
      order: 0,
    },
    VES: {
      isoNumeric: "928",
      name: "Venezuelan Bolívar Soberano",
      symbol: "Bs",
      flagIcon: "circle-flags:ve",
      popular: false,
      order: 0,
    },
    VND: {
      isoNumeric: "704",
      name: "Vietnamese Đồng",
      symbol: "₫",
      flagIcon: "circle-flags:vn",
      popular: false,
      order: 0,
    },
    VUV: {
      isoNumeric: "548",
      name: "Vanuatu Vatu",
      symbol: "Vt",
      flagIcon: "circle-flags:vu",
      popular: false,
      order: 0,
    },
    WST: {
      isoNumeric: "882",
      name: "Samoan Tala",
      symbol: "T",
      flagIcon: "circle-flags:ws",
      popular: false,
      order: 0,
    },
    XAF: {
      isoNumeric: "950",
      name: "Central African CFA Franc",
      symbol: "CFA",
      flagIcon: "circle-flags:cm",
      popular: false,
      order: 0,
    },
    XAG: {
      isoNumeric: "961",
      name: "Silver (Troy Ounce)",
      symbol: "oz t",
      flagIcon: "ion:star",
      popular: false,
      order: 0,
    },
    XAU: {
      isoNumeric: "959",
      name: "Gold (Troy Ounce)",
      symbol: "oz t",
      flagIcon: "ion:star",
      popular: false,
      order: 0,
    },
    XCD: {
      isoNumeric: "951",
      name: "East Caribbean Dollar",
      symbol: "$",
      flagIcon: "circle-flags:ai",
      popular: false,
      order: 0,
    },
    XCG: {
      isoNumeric: "532",
      name: "Caribbean Guilder",
      symbol: "Cg",
      flagIcon: "ion:star",
      popular: false,
      order: 0,
    },
    XDR: {
      isoNumeric: "960",
      name: "Special Drawing Rights",
      symbol: "SDR",
      flagIcon: "ion:star",
      popular: false,
      order: 0,
    },
    XOF: {
      isoNumeric: "952",
      name: "West African CFA Franc",
      symbol: "Fr",
      flagIcon: "circle-flags:bj",
      popular: false,
      order: 0,
    },
    XPD: {
      isoNumeric: "964",
      name: "Palladium",
      symbol: "oz t",
      flagIcon: "ion:star",
      popular: false,
      order: 0,
    },
    XPF: {
      isoNumeric: "953",
      name: "CFP Franc",
      symbol: "Fr",
      flagIcon: "circle-flags:pf",
      popular: false,
      order: 0,
    },
    XPT: {
      isoNumeric: "962",
      name: "Platinum",
      symbol: "oz t",
      flagIcon: "ion:star",
      popular: false,
      order: 0,
    },
    YER: {
      isoNumeric: "886",
      name: "Yemeni Rial",
      symbol: "﷼",
      flagIcon: "circle-flags:ye",
      popular: false,
      order: 0,
    },
    ZAR: {
      isoNumeric: "710",
      name: "South African Rand",
      symbol: "R",
      flagIcon: "circle-flags:za",
      popular: false,
      order: 0,
    },
    ZMW: {
      isoNumeric: "967",
      name: "Zambian Kwacha",
      symbol: "K",
      flagIcon: "circle-flags:zm",
      popular: false,
      order: 0,
    },
    ZWG: {
      isoNumeric: "924",
      name: "Zimbabwe Gold",
      symbol: "ZiG",
      flagIcon: "circle-flags:zw",
      popular: false,
      order: 0,
    },
  };

export type CurrencyCode = keyof typeof currencyMeta;
