export const CurrencyCodes = ["AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHF", "CLP", "CNY", "COP", "CRC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VES", "VND", "VUV", "WST", "XAF", "XCD", "XOF", "XPF", "YER", "ZAR", "ZMW", "ZWG"] as const;

export const CountryCodes = ["AF", "AX", "AL", "DZ", "AS", "AD", "AO", "AI", "AQ", "AG", "AR", "AM", "AW", "AU", "AT", "AZ", "BS", "BH", "BD", "BB", "BY", "BE", "BZ", "BJ", "BM", "BT", "BO", "BQ", "BA", "BW", "BV", "BR", "IO", "BN", "BG", "BF", "BI", "CV", "KH", "CM", "CA", "KY", "CF", "TD", "CL", "CN", "CX", "CC", "CO", "KM", "CD", "CG", "CK", "CR", "CI", "HR", "CU", "CW", "CY", "CZ", "DK", "DJ", "DM", "DO", "EC", "EG", "EU", "SV", "GQ", "ER", "EE", "SZ", "ET", "FK", "FO", "FJ", "FI", "FR", "GF", "PF", "TF", "GA", "GM", "GE", "DE", "GH", "GI", "GR", "GL", "GD", "GP", "GU", "GT", "GG", "GN", "GW", "GY", "HT", "HM", "VA", "HN", "HK", "HU", "IS", "IN", "ID", "IR", "IQ", "IE", "IM", "IL", "IT", "JM", "JP", "JE", "JO", "KZ", "KE", "KI", "KP", "KR", "KW", "KG", "LA", "LV", "LB", "LS", "LR", "LY", "LI", "LT", "LU", "MO", "MG", "MK", "MW", "MY", "MV", "ML", "MT", "MH", "MQ", "MR", "MU", "YT", "MX", "FM", "MD", "MC", "MN", "ME", "MS", "MA", "MZ", "MM", "NA", "NR", "NP", "NL", "NC", "NZ", "NI", "NE", "NG", "NU", "NF", "MP", "NO", "OM", "PK", "PW", "PS", "PA", "PG", "PY", "PE", "PH", "PN", "PL", "PT", "PR", "QA", "RE", "RO", "RU", "RW", "BL", "SH", "KN", "LC", "MF", "PM", "VC", "WS", "SM", "ST", "SA", "SN", "RS", "SC", "SL", "SG", "SX", "SK", "SI", "SB", "SO", "ZA", "GS", "SS", "ES", "LK", "SD", "SR", "SJ", "SE", "CH", "SY", "TW", "TJ", "TZ", "TH", "TL", "TG", "TK", "TO", "TT", "TN", "TR", "TM", "TC", "TV", "UG", "UA", "AE", "GB", "UM", "US", "UY", "UZ", "VU", "VE", "VN", "VG", "VI", "WF", "EH", "YE", "ZM", "ZW"] as const;

export type CurrencyCode = typeof CurrencyCodes[number];
export type CountryCode = typeof CountryCodes[number];

export type CurrencyToCountries = Record<CurrencyCode, CountryCode[]>;

export const currencyToCountryMap: CurrencyToCountries = {
  AED: ["AE"],
  AFN: ["AF"],
  ALL: ["AL"],
  AMD: ["AM"],
  ANG: ["CW", "SX"],
  AOA: ["AO"],
  ARS: ["AR"],
  AUD: ["AU", "CC", "CX", "HM", "KI", "NF", "NR", "TV"],
  AWG: ["AW"],
  AZN: ["AZ"],
  BAM: ["BA"],
  BBD: ["BB"],
  BDT: ["BD"],
  BGN: ["BG"],
  BHD: ["BH"],
  BIF: ["BI"],
  BMD: ["BM"],
  BND: ["BN"],
  BOB: ["BO"],
  BRL: ["BR"],
  BSD: ["BS"],
  BTN: ["BT"],
  BWP: ["BW"],
  BYN: ["BY"],
  BZD: ["BZ"],
  CAD: ["CA"],
  CDF: ["CD"],
  CHF: ["CH", "LI"],
  CLP: ["CL"],
  CNY: ["CN"],
  COP: ["CO"],
  CRC: ["CR"],
  CUP: ["CU"],
  CVE: ["CV"],
  CZK: ["CZ"],
  DJF: ["DJ"],
  DKK: ["DK", "FO", "GL"],
  DOP: ["DO"],
  DZD: ["DZ"],
  EGP: ["EG"],
  ERN: ["ER"],
  ETB: ["ET"],
  EUR: ["EU", "AT", "BE", "CY", "DE", "EE", "ES", "FI", "FR", "GR", "HR", "IE", "IT", "LT", "LU", "LV", "MT", "NL", "PT", "SI", "SK", "VA"],
  FJD: ["FJ"],
  FKP: ["FK"],
  GBP: ["GB", "GG", "GS", "IM", "JE"],
  GEL: ["GE"],
  GHS: ["GH"],
  GIP: ["GI"],
  GMD: ["GM"],
  GNF: ["GN"],
  GTQ: ["GT"],
  GYD: ["GY"],
  HKD: ["HK"],
  HNL: ["HN"],
  HTG: ["HT"],
  HUF: ["HU"],
  IDR: ["ID"],
  ILS: ["IL", "PS"],
  INR: ["IN", "BT"],
  IQD: ["IQ"],
  IRR: ["IR"],
  ISK: ["IS"],
  JMD: ["JM"],
  JOD: ["JO"],
  JPY: ["JP"],
  KES: ["KE"],
  KGS: ["KG"],
  KHR: ["KH"],
  KMF: ["KM"],
  KPW: ["KP"],
  KRW: ["KR"],
  KWD: ["KW"],
  KYD: ["KY"],
  KZT: ["KZ"],
  LAK: ["LA"],
  LBP: ["LB"],
  LKR: ["LK"],
  LRD: ["LR"],
  LSL: ["LS"],
  LYD: ["LY"],
  MAD: ["MA", "EH"],
  MDL: ["MD"],
  MGA: ["MG"],
  MKD: ["MK"],
  MMK: ["MM"],
  MNT: ["MN"],
  MOP: ["MO"],
  MRU: ["MR"],
  MUR: ["MU"],
  MVR: ["MV"],
  MWK: ["MW"],
  MXN: ["MX"],
  MYR: ["MY"],
  MZN: ["MZ"],
  NAD: ["NA"],
  NGN: ["NG"],
  NIO: ["NI"],
  NOK: ["NO", "BV", "SJ"],
  NPR: ["NP"],
  NZD: ["NZ", "CK", "NU", "PN", "TK"],
  OMR: ["OM"],
  PAB: ["PA"],
  PEN: ["PE"],
  PGK: ["PG"],
  PHP: ["PH"],
  PKR: ["PK"],
  PLN: ["PL"],
  PYG: ["PY"],
  QAR: ["QA"],
  RON: ["RO"],
  RSD: ["RS"],
  RUB: ["RU"],
  RWF: ["RW"],
  SAR: ["SA"],
  SBD: ["SB"],
  SCR: ["SC"],
  SDG: ["SD"],
  SEK: ["SE"],
  SGD: ["SG"],
  SHP: ["SH"],
  SLE: ["SL"],
  SOS: ["SO"],
  SRD: ["SR"],
  SSP: ["SS"],
  STN: ["ST"],
  SVC: ["SV"],
  SYP: ["SY"],
  SZL: ["SZ"],
  THB: ["TH"],
  TJS: ["TJ"],
  TMT: ["TM"],
  TND: ["TN"],
  TOP: ["TO"],
  TRY: ["TR"],
  TTD: ["TT"],
  TWD: ["TW"],
  TZS: ["TZ"],
  UAH: ["UA"],
  UGX: ["UG"],
  USD: ["US", "AS", "BM", "IO", "GU", "MH", "FM", "MP", "PW", "PR", "TC", "UM", "VG", "VI"],
  UYU: ["UY"],
  UZS: ["UZ"],
  VES: ["VE"],
  VND: ["VN"],
  VUV: ["VU"],
  WST: ["WS"],
  XAF: ["CM", "CF", "TD", "CG", "GQ", "GA"],
  XCD: ["AI", "AG", "DM", "GD", "MS", "KN", "LC", "VC"],
  XOF: ["BJ", "BF", "CI", "GW", "ML", "NE", "SN", "TG"],
  XPF: ["PF", "NC", "WF"],
  YER: ["YE"],
  ZAR: ["ZA", "LS", "NA", "SZ"],
  ZMW: ["ZM"],
  ZWG: ["ZW"],
};
