export type CurrencyToCountries = Record<CurrencyCode, CountryCode[]>;

export const currencyToCountryMap: CurrencyToCountries = {
  AED: ["AE"],
  AFN: ["AF"],
  ALL: ["AL"],
  AMD: ["AM"],
  ANG: ["CW", "SX"],
  AOA: ["AO"],
  ARS: ["AR"],
  AUD: ["AU", "CC", "CX", "HM", "KI", "NF", "NR", "TV"],
  AWG: ["AW"],
  AZN: ["AZ"],
  BAM: ["BA"],
  BBD: ["BB"],
  BDT: ["BD"],
  BGN: ["BG"],
  BHD: ["BH"],
  BIF: ["BI"],
  BMD: ["BM"],
  BND: ["BN"],
  BOB: ["BO"],
  BRL: ["BR"],
  BSD: ["BS"],
  BTN: ["BT"],
  BWP: ["BW"],
  BYN: ["BY"],
  BZD: ["BZ"],
  CAD: ["CA"],
  CDF: ["CD"],
  CHF: ["CH", "LI"],
  CLP: ["CL"],
  CNY: ["CN"],
  COP: ["CO"],
  CRC: ["CR"],
  CUP: ["CU"],
  CVE: ["CV"],
  CZK: ["CZ"],
  DJF: ["DJ"],
  DKK: ["DK", "FO", "GL"],
  DOP: ["DO"],
  DZD: ["DZ"],
  EGP: ["EG"],
  ERN: ["ER"],
  ETB: ["ET"],
  EUR: ["EU", "AT", "BE", "CY", "DE", "EE", "ES", "FI", "FR", "GR", "HR", "IE", "IT", "LT", "LU", "LV", "MT", "NL", "PT", "SI", "SK", "VA"],
  FJD: ["FJ"],
  FKP: ["FK"],
  GBP: ["GB", "GG", "GS", "IM", "JE"],
  GEL: ["GE"],
  GHS: ["GH"],
  GIP: ["GI"],
  GMD: ["GM"],
  GNF: ["GN"],
  GTQ: ["GT"],
  GYD: ["GY"],
  HKD: ["HK"],
  HNL: ["HN"],
  HTG: ["HT"],
  HUF: ["HU"],
  IDR: ["ID"],
  ILS: ["IL", "PS"],
  INR: ["IN", "BT"],
  IQD: ["IQ"],
  IRR: ["IR"],
  ISK: ["IS"],
  JMD: ["JM"],
  JOD: ["JO"],
  JPY: ["JP"],
  KES: ["KE"],
  KGS: ["KG"],
  KHR: ["KH"],
  KMF: ["KM"],
  KPW: ["KP"],
  KRW: ["KR"],
  KWD: ["KW"],
  KYD: ["KY"],
  KZT: ["KZ"],
  LAK: ["LA"],
  LBP: ["LB"],
  LKR: ["LK"],
  LRD: ["LR"],
  LSL: ["LS"],
  LYD: ["LY"],
  MAD: ["MA", "EH"],
  MDL: ["MD"],
  MGA: ["MG"],
  MKD: ["MK"],
  MMK: ["MM"],
  MNT: ["MN"],
  MOP: ["MO"],
  MRU: ["MR"],
  MUR: ["MU"],
  MVR: ["MV"],
  MWK: ["MW"],
  MXN: ["MX"],
  MYR: ["MY"],
  MZN: ["MZ"],
  NAD: ["NA"],
  NGN: ["NG"],
  NIO: ["NI"],
  NOK: ["NO", "BV", "SJ"],
  NPR: ["NP"],
  NZD: ["NZ", "CK", "NU", "PN", "TK"],
  OMR: ["OM"],
  PAB: ["PA"],
  PEN: ["PE"],
  PGK: ["PG"],
  PHP: ["PH"],
  PKR: ["PK"],
  PLN: ["PL"],
  PYG: ["PY"],
  QAR: ["QA"],
  RON: ["RO"],
  RSD: ["RS"],
  RUB: ["RU"],
  RWF: ["RW"],
  SAR: ["SA"],
  SBD: ["SB"],
  SCR: ["SC"],
  SDG: ["SD"],
  SEK: ["SE"],
  SGD: ["SG"],
  SHP: ["SH"],
  SLE: ["SL"],
  SOS: ["SO"],
  SRD: ["SR"],
  SSP: ["SS"],
  STN: ["ST"],
  SVC: ["SV"],
  SYP: ["SY"],
  SZL: ["SZ"],
  THB: ["TH"],
  TJS: ["TJ"],
  TMT: ["TM"],
  TND: ["TN"],
  TOP: ["TO"],
  TRY: ["TR"],
  TTD: ["TT"],
  TWD: ["TW"],
  TZS: ["TZ"],
  UAH: ["UA"],
  UGX: ["UG"],
  USD: ["US", "AS", "BM", "IO", "GU", "MH", "FM", "MP", "PW", "PR", "TC", "UM", "VG", "VI"],
  UYU: ["UY"],
  UZS: ["UZ"],
  VES: ["VE"],
  VND: ["VN"],
  VUV: ["VU"],
  WST: ["WS"],
  XAF: ["CM", "CF", "TD", "CG", "GQ", "GA"],
  XCD: ["AI", "AG", "DM", "GD", "MS", "KN", "LC", "VC"],
  XOF: ["BJ", "BF", "CI", "GW", "ML", "NE", "SN", "TG"],
  XPF: ["PF", "NC", "WF"],
  YER: ["YE"],
  ZAR: ["ZA", "LS", "NA", "SZ"],
  ZMW: ["ZM"],
  ZWG: ["ZW"],
};
